project_id = "personal-algorithm"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320

[studio]
api_url = "http://127.0.0.1:54321"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:3000/**",
  "http://127.0.0.1:3000/**"
]

[auth.external.google]
enabled = true
client_id = "set-your-google-client-id"
secret = "set-your-google-client-secret"
