import test from 'node:test';import assert from 'node:assert/strict';import{isScoreTraceConsistent,replayPersonalAlgorithmScore,scorePersonalAlgorithm,traceContributionTotal}from'../src/personal-algorithm-scorer.ts';
const state={schemaVersion:2,evidence:[{id:'e1',evidence:{kind:'interaction',content:{source:'youtube',externalId:'video-1'},exposureId:'exp-1',interaction:'watched',observedAt:'2026-09-26T10:00:00.000Z',provenance:{connector:'youtube',mechanism:'player_telemetry'}},confidence:1,retainedAt:'2026-09-26T10:00:01.000Z',retention:{policy:'default',expiresAt:null}}],graph:{nodes:[{id:'content:youtube:video-1',kind:'content',label:'Video 1',provenance:'explicit',confidence:1,attributes:{},createdAt:'2026-09-26T10:00:00.000Z',updatedAt:'2026-09-26T10:00:00.000Z'},{id:'creator:youtube:creator-1',kind:'creator',label:'Creator 1',provenance:'inferred',confidence:1,attributes:{},createdAt:'2026-09-26T10:00:00.000Z',updatedAt:'2026-09-26T10:00:00.000Z'}],edges:[{id:'edge:created-by:video-1:creator-1',sourceNodeId:'content:youtube:video-1',targetNodeId:'creator:youtube:creator-1',relation:'created_by',provenance:'inferred',confidence:1,evidenceIds:['e1'],attributes:{},createdAt:'2026-09-26T10:00:00.000Z',updatedAt:'2026-09-26T10:00:00.000Z'}],userEdits:[],revisions:[],currentRevision:7}};
const candidate={id:'candidate-1',content:{source:'youtube',externalId:'video-1'},nodeIds:['content:youtube:video-1'],creatorNodeId:'creator:youtube:creator-1'};
test('additive scoring reconciles exact contributions',()=>{const p={revision:'p1',baseScore:1,nodeWeights:{'content:youtube:video-1':2,'creator:youtube:creator-1':3},edgeRelationWeights:{created_by:4},feedback:[{id:'f1',contentId:'video-1',value:-.5,label:'less like this',evidenceIds:['e1']}],modes:{Work:{baseDelta:.25,nodeWeights:{'creator:youtube:creator-1':.75}}}};const r=scorePersonalAlgorithm(state,candidate,p,'Work');assert.equal(r.score,10.5);assert.equal(traceContributionTotal(r.trace),10.5);assert.equal(isScoreTraceConsistent(r.trace),true);assert.equal(r.trace.edgeContributions[0].evidenceIds[0],'e1');assert.equal(r.trace.modeContributions.length,2)});
test('exclusion and eligibility happen before scoring',()=>{const p={revision:'p2',baseScore:100,exclusions:{creatorNodeIds:['creator:youtube:creator-1']},eligibility:{requiredNodeIds:['missing']}};const r=scorePersonalAlgorithm(state,candidate,p);assert.equal(r.trace.policyOutcome,'excluded');assert.equal(r.score,0);assert.equal(r.trace.nodeContributions.length,0)});
test('suppression is represented as a contribution',()=>{const p={revision:'p3',baseScore:1,nodeWeights:{'content:youtube:video-1':1},suppression:{belowScore:5}};const r=scorePersonalAlgorithm(state,candidate,p);assert.equal(r.trace.policyOutcome,'suppressed');assert.equal(r.score,0);assert.equal(r.trace.suppressionContributions[0].value,-2);assert.equal(isScoreTraceConsistent(r.trace),true)});
test('replay reproduces score and trace identity',()=>{const p={revision:'p4',baseScore:2,nodeWeights:{'content:youtube:video-1':3}};const a=scorePersonalAlgorithm(state,candidate,p),b=replayPersonalAlgorithmScore(state,candidate,p);assert.equal(b.score,a.score);assert.equal(b.trace.id,a.trace.id);assert.equal(b.trace.graphRevision,7);assert.equal(b.trace.evidenceRevision,a.trace.evidenceRevision)});
test('feedback changes trace identity',()=>{const p={revision:'p-feedback',baseScore:1};const a=scorePersonalAlgorithm(state,candidate,p,'default',[]),b=scorePersonalAlgorithm(state,candidate,p,'default',[{id:'f1',contentId:'video-1',value:2}]);assert.notEqual(a.trace.id,b.trace.id);assert.notEqual(a.score,b.score)});
test('insertion order does not change trace',()=>{const p={revision:'p5',edgeRelationWeights:{created_by:2}};const reversed={...state,graph:{...state.graph,nodes:[...state.graph.nodes].reverse(),edges:[...state.graph.edges].reverse()}};const a=scorePersonalAlgorithm(state,candidate,p),b=scorePersonalAlgorithm(reversed,candidate,p);assert.equal(b.trace.id,a.trace.id);assert.deepEqual(b.trace.edgeContributions,a.trace.edgeContributions)});
