import test from 'node:test';
import assert from 'node:assert/strict';
import { evaluateReplacementStability } from '@repo/recommender-core';

import { buildExplanationViewModel, buildModeSupplyPlan, createReplacementSelectionSeed, createReplacementSlotId, getCandidateAcquisitionLabel, getContentPresentationLabel, getNativeCardDecision, getReplacementCandidates, getReplacementPresentationMetadata, getReplacementTextMetadata, getShelfCandidates, getSourceShelfHideReason, isDurableModeGroundedItem, isProvisionalDurableModeRelevantItem, isRenderContextStale, isReplacementEligibleNativeDecision, isStableReplacementCandidateAvailableToSource, isStableReplacementCandidateEligible, isStableReplacementSourceSlotPrebound, keepOutermostElements, navigationFinishRerankReason, planReplacementAssignments, replacementQuota, selectFeedMixAssignments, selectOpportunisticReplacementAssignments, selectOpportunisticReplacementTargets, selectRetrievedDiscoveryAssignments, shouldClearSourceFilteredPresentation, shouldInvalidateStableReplacementBindings, shouldPreserveReplacementOwnedPresentation } from './youtube-ux.ts';

const lowScoreFeed = [
  { external_id: 'video-a', title: 'Video A', score: 6, visible: true },
  { external_id: 'video-b', title: 'Video B', score: 1, visible: true },
  { external_id: 'video-c', title: 'Video C', score: -9, visible: true },
];

test('MVP scores are eligible for shelf presentation', () => {
  assert.deepEqual(
    getShelfCandidates(lowScoreFeed, 6, [], 0),
    [lowScoreFeed[0], lowScoreFeed[1]],
  );
});

test('explanation view model preserves graph paths, acquisition boundary, and exact contribution values', () => {
  const view = buildExplanationViewModel({
    external_id: 'video-a',
    score: 72,
    traceId: 'trace-a',
    explanation: {
      rawScore: 14.5,
      displayScore: 72,
      graphRevision: 12,
      acquisitionMechanism: 'web_search',
      contributions: [
        { label: 'semantic neighbourhood: local AI', value: 10, kind: 'feature', sourceId: 'topic:local-ai', evidenceIds: ['e1'] },
        { label: 'explicit feedback: not_interested', value: -5, kind: 'feedback', evidenceIds: ['e2'] },
      ],
      matchedPaths: [
        {
          nodeIds: ['topic:local-ai', 'creator:youtube:example'],
          nodeLabels: ['Local AI', 'Example Creator'],
          edgeIds: ['edge:created_by:a'],
          evidenceIds: ['e1', 'e2'],
        },
      ],
      modeGrounding: null,
      evidenceRecords: [
        {
          evidenceId: 'e1',
          kind: 'interaction',
          interaction: 'watched',
          connector: 'youtube',
          mechanism: 'history_dom',
          observedAt: '2026-09-30T12:00:00.000Z',
          confidence: 0.9,
          externalId: 'past-video',
          title: 'Past video',
        },
      ],
    },
  });

  assert.equal(view.scoreLine, 'Score 72/100 · raw 14.5 · graph r12');
  assert.equal(
    view.acquisitionLine,
    'YouTube search discovery · acquisition source is not preference evidence',
  );
  assert.deepEqual(
    view.pathLines,
    ['Graph path: Local AI ↔ Example Creator · 2 evidence items'],
  );
  assert.deepEqual(
    view.contributionLines,
    [
      'Concept: local AI: +10',
      'explicit feedback: not interested: -5',
    ],
  );
  assert.deepEqual(
    view.miniNodes,
    [
      { id: 'video-a', label: 'This video', kind: 'video' },
      { id: 'contribution:0:local AI', label: 'local AI', kind: 'concept' },
      { id: 'path:edge:created_by:a:1:Example Creator', label: 'Example Creator', kind: 'creator' },
    ],
  );
  assert.equal(view.contributions[0].evidenceCount, 1);
  assert.equal(view.contributions[0].actionLabel, 'Reduce');
  assert.equal(view.contributions[0].targetKind, 'node');
  assert.equal(view.contributions[0].targetId, 'topic:local-ai');
  assert.deepEqual(view.evidenceRecords, [
    {
      evidenceId: 'e1',
      kind: 'interaction',
      interaction: 'watched',
      connector: 'youtube',
      mechanism: 'history_dom',
      observedAt: '2026-09-30T12:00:00.000Z',
      confidence: 0.9,
      externalId: 'past-video',
      title: 'Past video',
    },
  ]);
  assert.equal(view.graphRevision, 12);
  assert.equal(view.traceId, 'trace-a');
});

test('Why-this marks caption-assisted semantics as derived input rather than preference evidence', () => {
  const view = buildExplanationViewModel({
    external_id: 'captioned-video',
    score: 65,
    traceId: 'trace-caption',
    explanation: {
      rawScore: 9,
      displayScore: 65,
      graphRevision: 13,
      acquisitionMechanism: 'observed_dom',
      semanticInputSources: ['metadata', 'transcript'],
      transcriptSource: 'youtube_caption_track',
      transcriptLanguage: 'en',
      transcriptAutoGenerated: true,
      contributions: [],
      matchedPaths: [],
      modeGrounding: null,
      historySupport: null,
      evidenceRecords: [],
    },
  });

  assert.equal(
    view.semanticInputLine,
    'Semantic input: metadata + YouTube captions · language en · auto-generated captions · caption text assists local semantic matching; it is not preference evidence',
  );
});

test('exact evidence records are sorted newest-first and remain individually addressable', () => {
  const view = buildExplanationViewModel({
    external_id: 'video-evidence',
    score: 60,
    traceId: 'trace-evidence',
    explanation: {
      rawScore: 7,
      displayScore: 60,
      graphRevision: 22,
      acquisitionMechanism: 'observed_dom',
      contributions: [],
      matchedPaths: [],
      modeGrounding: null,
      evidenceRecords: [
        {
          evidenceId: 'older',
          kind: 'exposure',
          interaction: null,
          connector: 'youtube',
          mechanism: 'home_dom',
          observedAt: '2026-09-30T10:00:00.000Z',
          confidence: 0.8,
          externalId: 'video-evidence',
          title: 'Current video exposure',
        },
        {
          evidenceId: 'newer',
          kind: 'interaction',
          interaction: 'watched',
          connector: 'youtube',
          mechanism: 'history_dom',
          observedAt: '2026-10-01T10:00:00.000Z',
          confidence: 1,
          externalId: 'past-video',
          title: 'Past watched video',
        },
      ],
    },
  });

  assert.deepEqual(view.evidenceRecords.map((record) => record.evidenceId), ['newer', 'older']);
});

test('exact negative graph contributions suggest the positive correction direction', () => {
  const view = buildExplanationViewModel({
    external_id: 'video-negative',
    title: 'Negative example',
    score: 40,
    traceId: 'trace-negative',
    explanation: {
      rawScore: -3,
      displayScore: 40,
      graphRevision: 7,
      acquisitionMechanism: 'observed_dom',
      contributions: [{
        label: 'topic: gaming',
        value: -3,
        kind: 'feature',
        sourceId: 'topic:gaming',
        evidenceIds: ['e-negative'],
      }],
      matchedPaths: [],
      modeGrounding: null,
      historySupport: null,
    },
  });

  assert.equal(view.contributions[0].actionLabel, 'Prefer');
  assert.equal(view.contributions[0].targetId, 'topic:gaming');
});

test('explanation display humanizes encoded graph labels and omits relation names from the mini graph', () => {
  const view = buildExplanationViewModel({
    external_id: 'video-x',
    title: 'Example video',
    channel_name: 'Angry Birds',
    score: 68,
    traceId: 'trace-x',
    explanation: {
      rawScore: 11,
      displayScore: 68,
      graphRevision: 4,
      acquisitionMechanism: 'observed_dom',
      contributions: [
        { label: 'creator: youtube:Angry%20Birds', value: 8, kind: 'node', evidenceIds: ['e1'] },
        { label: 'created_by', value: 2, kind: 'edge', evidenceIds: ['e1'] },
      ],
      matchedPaths: [{
        nodeIds: ['creator:youtube:Angry%20Birds', 'topic:games'],
        nodeLabels: ['youtube:Angry%20Birds', 'Gaming'],
        edgeIds: ['edge:games'],
        evidenceIds: ['e1', 'e2'],
      }],
      modeGrounding: null,
      historySupport: {
        scoreSharePercent: 67,
        matchedVideoCount: 1,
        matches: [{
          evidenceId: 'e1',
          externalId: 'past-video',
          title: 'Past Angry Birds video',
          observedAt: '2026-09-29T12:00:00.000Z',
          interaction: 'watched',
          matchedBy: ['creator: Angry Birds'],
        }],
      },
    },
  });

  assert.equal(view.pathLines[0], 'Graph path: Angry Birds ↔ Gaming · 2 evidence items');
  assert.equal(view.contributionLines.some((line) => /created by/i.test(line)), false);
  assert.equal(view.miniNodes.some((node) => node.label === 'created by'), false);
  assert.equal(view.miniNodes.some((node) => node.label === 'Angry Birds'), true);
  assert.equal(view.historyScoreSharePercent, 67);
  assert.equal(view.historyMatches[0].title, 'Past Angry Birds video');
});

test('Why-this omits the current content node even when its graph label is the full video title', () => {
  const view = buildExplanationViewModel({
    external_id: 'hfAJNg5Zbdo',
    title: 'There’s Something Evil Happening To People... Be Careful 15 minutes',
    channel_name: 'Everyday Life Unfiltered',
    score: 65,
    traceId: 'trace-current-node',
    explanation: {
      rawScore: 8,
      displayScore: 65,
      graphRevision: 18,
      acquisitionMechanism: 'observed_dom',
      contributions: [
        {
          label: 'hfAJNg5Zbdo',
          value: 1,
          kind: 'node',
          sourceId: 'content:youtube:hfAJNg5Zbdo',
          evidenceIds: ['e-current'],
        },
        {
          label: 'creator: Everyday Life Unfiltered',
          value: 8,
          kind: 'node',
          sourceId: 'creator:youtube:everyday',
          evidenceIds: ['e-history'],
        },
      ],
      matchedPaths: [{
        nodeIds: [
          'content:youtube:hfAJNg5Zbdo',
          'creator:youtube:everyday',
        ],
        nodeLabels: [
          'There’s Something Evil Happening To People... Be Careful 15 minutes',
          'Everyday Life Unfiltered',
        ],
        edgeIds: ['edge:created-by'],
        evidenceIds: ['e-current'],
      }],
      modeGrounding: null,
      historySupport: null,
    },
  });

  assert.equal(view.contributionLines.some((line) => line.includes('hfAJNg5Zbdo')), false);
  assert.equal(
    view.miniNodes.filter((node) => node.label.includes('Something Evil')).length,
    0,
  );
  assert.equal(
    view.miniNodes.filter((node) => node.label === 'Everyday Life Unfiltered').length,
    1,
  );
});

test('explanation provenance uses user-facing labels without becoming a ranking reason', () => {
  assert.equal(
    buildExplanationViewModel({
      score: 68,
      explanation: {
        rawScore: 11,
        displayScore: 68,
        graphRevision: 9,
        acquisitionMechanism: 'observed_dom',
        contributions: [],
        matchedPaths: [],
        modeGrounding: null,
      },
    }).acquisitionLine,
    'YouTube native page · acquisition source is not preference evidence',
  );
});

test('replacement candidates require current trace and eligible policy outcome', () => {
  const items = [
    { external_id: 'video-a', title: 'A', score: 80, visible: true, traceId: 'trace-a', policyOutcome: 'eligible' },
    { external_id: 'video-b', title: 'B', score: 90, visible: true },
    { external_id: 'video-c', title: 'C', score: 90, visible: true, traceId: 'trace-c', suppressed: true, policyOutcome: 'suppressed' },
    { external_id: 'video-d', title: 'D', score: 70, visible: true, traceId: 'trace-d', policyOutcome: 'eligible' },
  ];
  assert.deepEqual(
    getReplacementCandidates(items, ['video-a'], 6, 52).map((item) => item.external_id),
    ['video-d'],
  );
});

test('feed mix replacement ordering is stable and does not depend on viewport layout state', () => {
  const targets = [
    { externalId: 'offscreen-low', score: 10, nativeIndex: 0 },
    { externalId: 'visible-high', score: 80, nativeIndex: 1 },
    { externalId: 'visible-low', score: 20, nativeIndex: 2 },
  ];
  const candidates = [
    { external_id: 'candidate-a', title: 'A', score: 90, visible: true, traceId: 'trace-a', policyOutcome: 'eligible' },
    { external_id: 'candidate-b', title: 'B', score: 85, visible: true, traceId: 'trace-b', policyOutcome: 'eligible' },
  ];

  const first = selectFeedMixAssignments(targets, candidates, 2, 100, 5);
  const second = selectFeedMixAssignments([...targets].reverse(), candidates, 2, 100, 5);

  assert.deepEqual(
    first.map((assignment) => assignment.target.externalId),
    ['offscreen-low', 'visible-low'],
  );
  assert.deepEqual(
    second.map((assignment) => assignment.target.externalId),
    ['offscreen-low', 'visible-low'],
  );
});

test('replacement assignment never reuses native source IDs or duplicate slots', () => {
  const items = [
    { external_id: 'native-a', title: 'Already native', score: 99, visible: true, traceId: 'trace-native', policyOutcome: 'eligible' },
    { external_id: 'candidate-a', title: 'Candidate A', score: 90, visible: true, traceId: 'trace-a', policyOutcome: 'eligible' },
    { external_id: 'candidate-b', title: 'Candidate B', score: 80, visible: true, traceId: 'trace-b', policyOutcome: 'eligible' },
  ];
  const slots = [
    { slotId: 'slot-1', sourceVideoId: 'native-a' },
    { slotId: 'slot-1', sourceVideoId: 'native-a' },
    { slotId: 'slot-2', sourceVideoId: 'native-b' },
  ];

  assert.deepEqual(
    planReplacementAssignments(items, slots, ['candidate-b'], 52).map((assignment) => ({
      slotId: assignment.slot.slotId,
      externalId: assignment.item.external_id,
    })),
    [{ slotId: 'slot-1', externalId: 'candidate-a' }],
  );
});

test('replacement assignment reports no work when there is no qualified candidate', () => {
  assert.deepEqual(
    planReplacementAssignments(
      [{ external_id: 'candidate-a', title: 'A', score: 51, visible: true, traceId: 'trace-a', policyOutcome: 'eligible' }],
      [{ slotId: 'slot-1', sourceVideoId: 'native-a' }],
      [],
      52,
    ),
    [],
  );
});


test('native-card policy gates run before score visibility', () => {
  assert.deepEqual(
    getNativeCardDecision(
      { external_id: 'video-a', title: 'Video A', score: 99, visible: true },
      { sourceFiltered: true, minimumVisibleScore: 0 },
    ),
    { action: 'hide', reason: 'source_filter' },
  );
  assert.deepEqual(
    getNativeCardDecision(
      { external_id: 'video-a', title: 'Video A', score: 99, visible: false },
      { sourceFiltered: false, minimumVisibleScore: 0 },
    ),
    { action: 'hide', reason: 'runtime_policy' },
  );
  assert.deepEqual(
    getNativeCardDecision(
      { external_id: 'video-a', title: 'Video A', score: 99, visible: true, suppressed: true, policyOutcome: 'suppressed' },
      { sourceFiltered: false, minimumVisibleScore: 0 },
    ),
    { action: 'hide', reason: 'runtime_policy' },
  );
});

test('native-card score threshold applies only to ranked candidates', () => {
  assert.deepEqual(
    getNativeCardDecision(
      { external_id: 'video-a', title: 'Video A', score: -9, visible: true },
      { sourceFiltered: false, minimumVisibleScore: 0 },
    ),
    { action: 'hide', reason: 'score' },
  );
  assert.deepEqual(
    getNativeCardDecision(
      { external_id: 'video-b', title: 'Video B', score: 1, visible: true },
      { sourceFiltered: false, minimumVisibleScore: 0 },
    ),
    { action: 'show', reason: 'ranked' },
  );
});

test('unmatched native cards pass through in degraded coverage', () => {
  assert.deepEqual(
    getNativeCardDecision(undefined, { sourceFiltered: false, minimumVisibleScore: 0 }),
    { action: 'show', reason: 'unmatched' },
  );
});

test('render context rejects stale generation, route, or mode', () => {
  const current = { generation: 4, routeKey: '/results?search_query=test', mode: 'Work' };
  assert.equal(isRenderContextStale(current, current), false);
  assert.equal(isRenderContextStale({ ...current, generation: 3 }, current), true);
  assert.equal(isRenderContextStale({ ...current, routeKey: '/' }, current), true);
  assert.equal(isRenderContextStale({ ...current, mode: 'Relax' }, current), true);
});


test('outermost-card selection removes nested duplicate presentation targets', () => {
  const outer = { id: 'outer' };
  const inner = { id: 'inner' };
  const sibling = { id: 'sibling' };
  const contains = (parent, child) => parent === outer && child === inner;

  assert.deepEqual(
    keepOutermostElements([outer, inner, sibling], contains),
    [outer, sibling],
  );
});


test('reactivation semantics require a fresh manual generation rather than stale mutation reuse', () => {
  const stale = { generation: 7, routeKey: '/', mode: 'Work' };
  const current = { generation: 8, routeKey: '/', mode: 'Work' };
  assert.equal(isRenderContextStale(stale, current), true);
});


test('replacement slot identity changes with generation, route, position, and source', () => {
  const base = createReplacementSlotId(4, '/', 2, 'native-a');
  assert.equal(base, '4|/|2|native-a');
  assert.notEqual(createReplacementSlotId(5, '/', 2, 'native-a'), base);
  assert.notEqual(createReplacementSlotId(4, '/results?q=x', 2, 'native-a'), base);
  assert.notEqual(createReplacementSlotId(4, '/', 3, 'native-a'), base);
  assert.notEqual(createReplacementSlotId(4, '/', 2, 'native-b'), base);
});


test('replacement presentation metadata is explicit and generation scoped', () => {
  const assignment = {
    slot: { slotId: '8|/|3|native-a', sourceVideoId: 'native-a' },
    item: {
      external_id: 'replacement-a',
      title: 'Replacement A',
      score: 6,
      traceId: 'trace-a',
      policyOutcome: 'eligible',
    },
  };
  assert.deepEqual(
    getReplacementPresentationMetadata(assignment, 8, 'Learning'),
    {
      generation: 8,
      mode: 'Learning',
      score: 6,
      traceId: 'trace-a',
      slotId: '8|/|3|native-a',
      sourceVideoId: 'native-a',
      replacementVideoId: 'replacement-a',
    },
  );
});


test('explicit source-filter hides are terminal and never become replacement slots', () => {
  assert.equal(
    isReplacementEligibleNativeDecision({ action: 'hide', reason: 'source_filter' }),
    false,
  );
  assert.equal(
    isReplacementEligibleNativeDecision({ action: 'hide', reason: 'runtime_policy' }),
    true,
  );
  assert.equal(
    isReplacementEligibleNativeDecision({ action: 'hide', reason: 'score' }),
    true,
  );
  assert.equal(
    isReplacementEligibleNativeDecision({ action: 'show', reason: 'ranked' }),
    false,
  );
});


test('active reranks preserve structurally hidden source shelves', () => {
  assert.equal(shouldClearSourceFilteredPresentation(false, true), false);
  assert.equal(shouldClearSourceFilteredPresentation(true, true), true);
  assert.equal(shouldClearSourceFilteredPresentation(false, false), true);
});

test('source shelf policy removes Shorts and Playables only when disabled', () => {
  assert.equal(
    getSourceShelfHideReason({ hasShortsLink: true }, { includeShorts: false }),
    'shorts',
  );
  assert.equal(
    getSourceShelfHideReason({ heading: 'Playables' }, { includePlayables: false }),
    'playables',
  );
  assert.equal(
    getSourceShelfHideReason({ hasPlayableLink: true }, { includePlayables: false }),
    'playables',
  );
  assert.equal(
    getSourceShelfHideReason(
      { heading: 'Playables', hasShortsLink: true, hasPlayableLink: true },
      { includeShorts: true, includePlayables: true },
    ),
    null,
  );
});


test('opportunistic replacements select only lower-scoring native cards', () => {
  const targets = [
    { externalId: 'native-a', score: 0, nativeIndex: 0 },
    { externalId: 'native-b', score: 2, nativeIndex: 1 },
    { externalId: 'native-c', score: 5, nativeIndex: 2 },
  ];
  const replacements = [
    { external_id: 'rss-a', title: 'RSS A', score: 6, visible: true, traceId: 'trace-a', policyOutcome: 'eligible' },
    { external_id: 'rss-b', title: 'RSS B', score: 3, visible: true, traceId: 'trace-b', policyOutcome: 'eligible' },
  ];

  assert.deepEqual(
    selectOpportunisticReplacementTargets(targets, replacements, 6, 5),
    [
      { externalId: 'native-a', score: 0, nativeIndex: 0 },
    ],
  );
});

test('opportunistic replacement requires configured score uplift', () => {
  assert.deepEqual(
    selectOpportunisticReplacementTargets(
      [{ externalId: 'native-a', score: 60, nativeIndex: 0 }],
      [{ external_id: 'rss-a', title: 'RSS A', score: 64, visible: true, traceId: 'trace-a', policyOutcome: 'eligible' }],
      6,
      5,
    ),
    [],
  );
  assert.deepEqual(
    selectOpportunisticReplacementTargets(
      [{ externalId: 'native-a', score: 60, nativeIndex: 0 }],
      [{ external_id: 'rss-a', title: 'RSS A', score: 65, visible: true, traceId: 'trace-a', policyOutcome: 'eligible' }],
      6,
      5,
    ),
    [{ externalId: 'native-a', score: 60, nativeIndex: 0 }],
  );
});


test('replacement text metadata always provides visible title and creator fallbacks', () => {
  assert.deepEqual(
    getReplacementTextMetadata({ title: '  Video title  ', channel_name: ' Creator ', score: 72, rawScore: 14.5 }),
    { title: 'Video title', creator: 'Creator', displayScore: 72, rawScore: 14.5 },
  );
  assert.deepEqual(
    getReplacementTextMetadata({ title: '', channel_name: null, score: 50 }),
    { title: 'Recommended video', creator: 'Unknown creator', displayScore: 50, rawScore: null },
  );
});


test('soft rerank cleanup preserves replacement-owned presentation UI', () => {
  assert.equal(
    shouldPreserveReplacementOwnedPresentation(true, true),
    true,
  );
  assert.equal(
    shouldPreserveReplacementOwnedPresentation(true, false),
    false,
  );
  assert.equal(
    shouldPreserveReplacementOwnedPresentation(false, true),
    false,
  );
});

test('navigation finish does not double-invalidate when navigation start already cleared bindings', () => {
  assert.equal(navigationFinishRerankReason(true), 'manual');
  assert.equal(navigationFinishRerankReason(false), 'navigation');
});

test('ordinary rerank causes preserve stable replacement bindings', () => {
  for (const reason of ['mutation', 'metadata', 'semantic', 'retrieval', 'manual']) {
    assert.equal(
      shouldInvalidateStableReplacementBindings(reason),
      false,
      `${reason} should preserve bindings`,
    );
  }

  for (const reason of ['navigation', 'mode', 'feedback', 'graph', 'policy', 'feed_mix', 'lifecycle']) {
    assert.equal(
      shouldInvalidateStableReplacementBindings(reason),
      true,
      `${reason} should invalidate bindings`,
    );
  }
});

test('stable candidate ownership allows the incumbent source but blocks another source', () => {
  const ownerByCandidateId = new Map([
    ['replacement-a', 'native-a'],
    ['replacement-b', 'native-b'],
  ]);

  assert.equal(
    isStableReplacementCandidateAvailableToSource(
      'replacement-a',
      'native-a',
      ownerByCandidateId,
    ),
    true,
  );
  assert.equal(
    isStableReplacementCandidateAvailableToSource(
      'replacement-a',
      'native-b',
      ownerByCandidateId,
    ),
    false,
  );
  assert.equal(
    isStableReplacementCandidateAvailableToSource(
      'replacement-c',
      'native-c',
      ownerByCandidateId,
    ),
    true,
  );
});

test('policy-created source slots keep their own prebound stable candidate', () => {
  assert.equal(
    isStableReplacementSourceSlotPrebound(
      'replacement-a',
      'replacement-a',
      true,
    ),
    true,
  );
  assert.equal(
    isStableReplacementSourceSlotPrebound(
      'replacement-b',
      'replacement-a',
      true,
    ),
    false,
  );
  assert.equal(
    isStableReplacementSourceSlotPrebound(
      'replacement-a',
      'replacement-a',
      false,
    ),
    false,
  );
});

test('stable replacement candidate survives score and trace refresh while still eligible', () => {
  const mode = { id: 'mode:lofi', label: 'chill lofi', revision: 5 };
  const refreshed = {
    external_id: 'replacement-a',
    title: 'Replacement A enriched',
    score: 78,
    visible: true,
    suppressed: false,
    traceId: 'trace-new',
    policyOutcome: 'eligible',
    explanation: {
      rawScore: 12.4,
      displayScore: 78,
      graphRevision: 357,
      acquisitionMechanism: 'web_search',
      contributions: [],
      modeGrounding: {
        modeId: mode.id,
        modeRevision: mode.revision,
        total: 8,
        members: [{
          canonicalId: 'canonical:lofi',
          label: 'lofi',
          value: 8,
          sourceIds: ['topic:lofi'],
          evidenceIds: [],
        }],
      },
    },
  };

  assert.equal(isStableReplacementCandidateEligible(refreshed, {
    activeMode: mode,
    minimumScore: 55,
    nativeScore: 70,
    feedReplacementPercent: 50,
  }), true);

  assert.equal(isStableReplacementCandidateEligible({
    ...refreshed,
    score: 54,
  }, {
    activeMode: mode,
    minimumScore: 55,
    nativeScore: 40,
    feedReplacementPercent: 50,
  }), false);

  assert.equal(isStableReplacementCandidateEligible({
    ...refreshed,
    policyOutcome: 'excluded',
    visible: false,
  }, {
    activeMode: mode,
    minimumScore: 55,
    nativeScore: 40,
    feedReplacementPercent: 50,
  }), false);

  assert.equal(isStableReplacementCandidateEligible({
    ...refreshed,
    explanation: {
      ...refreshed.explanation,
      modeGrounding: {
        ...refreshed.explanation.modeGrounding,
        modeRevision: 4,
      },
    },
  }, {
    activeMode: mode,
    minimumScore: 55,
    nativeScore: 40,
    feedReplacementPercent: 50,
  }), false);

  assert.equal(isStableReplacementCandidateEligible({
    ...refreshed,
    score: 60,
  }, {
    activeMode: mode,
    minimumScore: 55,
    nativeScore: 90,
    feedReplacementPercent: 100,
  }), true);
});

test('provisional durable-mode relevance recognizes semantic category, mode similarity, and member-label title matches', () => {
  const mode = {
    id: 'mode:corporate',
    label: 'corporate culture',
    revision: 4,
    memberLabels: ['corporate culture', 'workplace culture'],
  };

  assert.equal(isProvisionalDurableModeRelevantItem({
    external_id: 'category-match',
    title: 'Inside a tech company',
    semantic_category: 'corporate culture',
    semantic_category_confidence: 0.6,
  }, mode), true);

  assert.equal(isProvisionalDurableModeRelevantItem({
    external_id: 'mode-similarity',
    title: 'How companies really work',
    semantic_mode_similarity: 0.68,
  }, mode), true);

  assert.equal(isProvisionalDurableModeRelevantItem({
    external_id: 'weak-similarity',
    title: 'Unrelated creator drama',
    semantic_mode_similarity: 0.51,
  }, mode), false);

  assert.equal(isProvisionalDurableModeRelevantItem({
    external_id: 'title-match',
    title: 'Why workplace culture is changing',
  }, mode), true);

  assert.equal(isProvisionalDurableModeRelevantItem({
    external_id: 'unrelated',
    title: 'Three hour lofi study mix',
    semantic_category: 'lofi beats',
    semantic_mode_similarity: 0.08,
  }, mode), false);
});

test('100 percent durable-mode replacement may use an eligible non-grounded fallback', () => {
  const mode = { id: 'mode:lofi', label: 'chill lofi', revision: 5 };
  const generic = {
    external_id: 'replacement-generic',
    title: 'Generic scored replacement',
    score: 61,
    visible: true,
    suppressed: false,
    traceId: 'trace-generic',
    policyOutcome: 'eligible',
    explanation: {
      rawScore: 3,
      displayScore: 61,
      graphRevision: 357,
      acquisitionMechanism: 'rss',
      contributions: [],
      modeGrounding: null,
    },
  };

  assert.equal(isStableReplacementCandidateEligible(generic, {
    activeMode: mode,
    minimumScore: 0,
    nativeScore: 90,
    feedReplacementPercent: 100,
  }), true);

  assert.equal(isStableReplacementCandidateEligible(generic, {
    activeMode: mode,
    minimumScore: 0,
    nativeScore: 40,
    feedReplacementPercent: 99,
  }), false);
});

test('replacement identity evaluator stays perfect across ordinary score and trace churn', () => {
  const before = {
    'native-a': 'replacement-a',
    'native-b': 'replacement-b',
    'native-c': 'replacement-c',
  };
  const afterMetadataAndSemanticRerank = {
    'native-a': 'replacement-a',
    'native-b': 'replacement-b',
    'native-c': 'replacement-c',
  };

  const metrics = evaluateReplacementStability(
    before,
    afterMetadataAndSemanticRerank,
  );
  assert.equal(metrics.commonSourceCount, 3);
  assert.equal(metrics.changedSourceCount, 0);
  assert.equal(metrics.stabilityRate, 1);
});

test('replacement candidate selection is stable for the same route', () => {
  const items = Array.from({ length: 8 }, (_, index) => ({
    external_id: `candidate-${index}`,
    title: `Candidate ${index}`,
    score: 80,
    visible: true,
    traceId: `trace-${index}`,
    policyOutcome: 'eligible',
  }));

  const seed = createReplacementSelectionSeed('/');
  const first = getReplacementCandidates(items, [], 3, 55, seed).map((item) => item.external_id);
  const replay = getReplacementCandidates(items, [], 3, 55, seed).map((item) => item.external_id);

  assert.deepEqual(replay, first);
  assert.equal(seed, '/');
  assert.equal(createReplacementSelectionSeed('/results?search_query=test'), '/results?search_query=test');
});


test('replacement tie breaking remains deterministic within one route', () => {
  const items = [
    { external_id: 'a', title: 'A', score: 80, visible: true, traceId: 'ta', policyOutcome: 'eligible' },
    { external_id: 'b', title: 'B', score: 79, visible: true, traceId: 'tb', policyOutcome: 'eligible' },
    { external_id: 'c', title: 'C', score: 78, visible: true, traceId: 'tc', policyOutcome: 'eligible' },
    { external_id: 'd', title: 'D', score: 77, visible: true, traceId: 'td', policyOutcome: 'eligible' },
    { external_id: 'e', title: 'E', score: 70, visible: true, traceId: 'te', policyOutcome: 'eligible' },
  ];

  const seed = createReplacementSelectionSeed('/');
  const first = getReplacementCandidates(items, [], 3, 55, seed).map((item) => item.external_id);
  const replay = getReplacementCandidates(items, [], 3, 55, seed).map((item) => item.external_id);

  assert.deepEqual(replay, first);
  assert.equal(first.includes('e'), false);
});


test('opportunistic replacement assignments bind the selected candidate to its native target', () => {
  const assignments = selectOpportunisticReplacementAssignments(
    [
      { externalId: 'native-low', score: 60, nativeIndex: 4 },
      { externalId: 'native-high', score: 75, nativeIndex: 8 },
    ],
    [
      { external_id: 'replacement-a', title: 'A', score: 82, visible: true, traceId: 'trace-a', policyOutcome: 'eligible' },
      { external_id: 'replacement-b', title: 'B', score: 69, visible: true, traceId: 'trace-b', policyOutcome: 'eligible' },
    ],
    2,
    5,
  );

  assert.equal(assignments.length, 1);
  assert.equal(assignments[0].target.externalId, 'native-low');
  assert.equal(assignments[0].item.external_id, 'replacement-a');
});


test('content presentation labels come from candidate classification, not active mode', () => {
  assert.equal(getContentPresentationLabel({ semantic_category: 'Gaming', semantic_category_confidence: 0.7 }), 'Gaming');
  assert.equal(getContentPresentationLabel({ semantic_category: 'French language', semantic_category_confidence: 0.7 }), 'French language');
  assert.equal(getContentPresentationLabel({ semantic_category: 'Ambiguous', semantic_category_confidence: 0.34 }), null);
  assert.equal(
    getContentPresentationLabel({
      semantic_category: null,
      semantic_category_confidence: 0,
      semantic_model_version: 'mxbai@test',
      content_label: 'learning',
      content_label_confidence: 0.9,
    }),
    null,
  );
  assert.equal(
    getContentPresentationLabel({ content_label: 'learning', content_label_confidence: 0.9 }),
    'Learning',
  );
  assert.equal(
    getContentPresentationLabel({ content_label: 'learning', content_label_confidence: 0.6 }),
    null,
  );
  assert.equal(
    getContentPresentationLabel({ score: 80 }),
    null,
  );
});

test('feed mix quota targets a bounded fraction and fills only qualified slots', () => {
  assert.equal(replacementQuota(0, 10), 0);
  assert.equal(replacementQuota(50, 10), 5);
  assert.equal(replacementQuota(100, 10), 10);
  assert.equal(replacementQuota(150, 10), 10);
  const targets = [
    { externalId: 'native-a', score: 70, nativeIndex: 0 },
    { externalId: 'native-b', score: 40, nativeIndex: 1 },
  ];
  const candidates = [
    { external_id: 'new-a', title: 'A', score: 60, visible: true, traceId: 'a', policyOutcome: 'eligible' },
    { external_id: 'new-b', title: 'B', score: 30, visible: true, traceId: 'b', policyOutcome: 'eligible' },
    { external_id: 'excluded', title: 'X', score: 99, visible: false, traceId: 'x', policyOutcome: 'excluded' },
  ];
  assert.deepEqual(selectFeedMixAssignments(targets, candidates, 0, 0, 5), []);
  assert.equal(selectFeedMixAssignments(targets, candidates, 2, 50, 5).length, 1);
  assert.equal(selectFeedMixAssignments(targets, candidates, 2, 100, 5).length, 2);
});


test('durable mode supply turns slider demand into native-first shortfall fill', () => {
  const mode = { id: 'mode:lofi', label: 'chill lofi', revision: 4 };
  const grounded = (id, score, revision = 4) => ({
    external_id: id,
    title: id,
    score,
    visible: true,
    traceId: `trace-${id}`,
    policyOutcome: 'eligible',
    explanation: {
      rawScore: score,
      displayScore: score,
      graphRevision: 12,
      acquisitionMechanism: null,
      contributions: [],
      modeGrounding: {
        modeId: 'mode:lofi',
        modeRevision: revision,
        total: 8,
        members: [{
          canonicalId: 'canonical:lofi',
          label: 'mode: chill lofi → canonical concept: lofi',
          value: 8,
          sourceIds: ['topic:lofi'],
          evidenceIds: ['e:lofi'],
        }],
      },
    },
  });

  const plan = buildModeSupplyPlan({
    mode,
    sliderPercent: 50,
    nativeIds: ['native-a', 'native-b', 'native-c', 'source-filtered-native'],
    eligibleNativeIds: ['native-a', 'native-b', 'native-c'],
    feedItems: [
      grounded('native-a', 70),
      { external_id: 'native-b', title: 'native-b', score: 70, visible: true, traceId: 'trace-native-b', policyOutcome: 'eligible' },
      grounded('source-filtered-native', 90),
      grounded('pool-a', 80),
      grounded('pool-b', 75),
    ],
    minimumReplacementScore: 55,
  });

  assert.equal(plan.eligibleNativeSlots, 3);
  assert.equal(plan.requestedModeSlots, 2);
  assert.equal(plan.nativeModeSupply, 1);
  assert.equal(plan.poolModeSupply, 2);
  assert.equal(plan.shortfall, 1);
  assert.equal(plan.fillLimit, 1);
  assert.deepEqual(plan.poolCandidates.map((item) => item.external_id), ['pool-a', 'pool-b']);
});

test('mode supply requires exact mode revision and ordinary replacement eligibility', () => {
  const mode = { id: 'mode:systems', label: 'Systems', revision: 3 };
  const item = (id, { revision = 3, score = 70, policyOutcome = 'eligible', visible = true } = {}) => ({
    external_id: id,
    title: id,
    score,
    visible,
    traceId: `trace-${id}`,
    policyOutcome,
    explanation: {
      rawScore: score,
      displayScore: score,
      graphRevision: 8,
      acquisitionMechanism: null,
      contributions: [],
      modeGrounding: {
        modeId: 'mode:systems',
        modeRevision: revision,
        total: 6,
        members: [{
          canonicalId: 'canonical:crdts',
          label: 'CRDTs',
          value: 6,
          sourceIds: ['topic:crdts'],
          evidenceIds: [],
        }],
      },
    },
  });

  assert.equal(isDurableModeGroundedItem(item('current'), mode), true);
  assert.equal(isDurableModeGroundedItem(item('stale', { revision: 2 }), mode), false);

  const plan = buildModeSupplyPlan({
    mode,
    sliderPercent: 100,
    nativeIds: ['native-current', 'native-stale'],
    eligibleNativeIds: ['native-current', 'native-stale'],
    feedItems: [
      item('native-current'),
      item('native-stale', { revision: 2 }),
      item('pool-good', { score: 70 }),
      item('pool-stale', { revision: 2, score: 99 }),
      item('pool-low', { score: 54 }),
      item('pool-excluded', { score: 99, policyOutcome: 'excluded', visible: false }),
    ],
    minimumReplacementScore: 55,
  });

  assert.equal(plan.requestedModeSlots, 2);
  assert.equal(plan.nativeModeSupply, 1);
  assert.equal(plan.poolModeSupply, 1);
  assert.equal(plan.shortfall, 1);
  assert.equal(plan.fillLimit, 2);
  assert.equal(plan.poolCandidates[0].external_id, 'pool-good');
});

test('higher durable-mode slider demand increases shortfall without inventing pool supply', () => {
  const mode = { id: 'mode:lofi', label: 'chill lofi', revision: 2 };
  const feedItems = [{
    external_id: 'native-a',
    title: 'native-a',
    score: 70,
    visible: true,
    traceId: 'trace-native-a',
    policyOutcome: 'eligible',
    explanation: {
      rawScore: 70,
      displayScore: 70,
      graphRevision: 10,
      acquisitionMechanism: null,
      contributions: [],
      modeGrounding: {
        modeId: mode.id,
        modeRevision: mode.revision,
        total: 7,
        members: [{
          canonicalId: 'canonical:lofi',
          label: 'lofi',
          value: 7,
          sourceIds: ['topic:lofi'],
          evidenceIds: [],
        }],
      },
    },
  }];
  const input = {
    mode,
    nativeIds: ['native-a', 'native-b', 'native-c', 'native-d', 'native-e'],
    eligibleNativeIds: ['native-a', 'native-b', 'native-c', 'native-d', 'native-e'],
    feedItems,
    minimumReplacementScore: 55,
  };

  const low = buildModeSupplyPlan({ ...input, sliderPercent: 20 });
  const high = buildModeSupplyPlan({ ...input, sliderPercent: 80 });
  assert.equal(low.requestedModeSlots, 1);
  assert.equal(low.shortfall, 0);
  assert.equal(high.requestedModeSlots, 4);
  assert.equal(high.shortfall, 3);
  assert.equal(high.poolModeSupply, 0);
  assert.equal(high.fillLimit, 0);
});


test('retrieved discovery can use a bounded exploration slot without provenance score bonus', () => {
  const targets = [
    { externalId: 'native-a', score: 60, nativeIndex: 0 },
    { externalId: 'native-b', score: 63, nativeIndex: 1 },
    { externalId: 'native-c', score: 66, nativeIndex: 2 },
  ];
  const candidates = [
    {
      external_id: 'search-a',
      title: 'Search A',
      score: 65,
      visible: true,
      traceId: 'trace-search-a',
      policyOutcome: 'eligible',
      acquisition_history: [{ mechanism: 'web_search', acquired_at: '2026-09-26T22:00:00.000Z' }],
    },
    {
      external_id: 'rss-b',
      title: 'RSS B',
      score: 64,
      visible: true,
      traceId: 'trace-rss-b',
      policyOutcome: 'eligible',
      provenance: { mechanism: 'rss', acquired_at: '2026-09-26T22:00:00.000Z' },
    },
    {
      external_id: 'observed-c',
      title: 'Observed C',
      score: 99,
      visible: true,
      traceId: 'trace-observed-c',
      policyOutcome: 'eligible',
      provenance: { mechanism: 'observed_dom', acquired_at: '2026-09-26T22:00:00.000Z' },
    },
  ];

  assert.deepEqual(
    selectRetrievedDiscoveryAssignments(targets, candidates, 2).map((assignment) => ({
      target: assignment.target.externalId,
      item: assignment.item.external_id,
    })),
    [
      { target: 'native-a', item: 'search-a' },
      { target: 'native-b', item: 'rss-b' },
    ],
  );
});

test('retrieved discovery never replaces a stronger native card', () => {
  assert.deepEqual(
    selectRetrievedDiscoveryAssignments(
      [{ externalId: 'native-a', score: 70, nativeIndex: 0 }],
      [{
        external_id: 'search-a',
        title: 'Search A',
        score: 69,
        visible: true,
        traceId: 'trace-search-a',
        policyOutcome: 'eligible',
        provenance: { mechanism: 'web_search', acquired_at: '2026-09-26T22:00:00.000Z' },
      }],
      2,
    ),
    [],
  );
});


test('candidate acquisition labels distinguish native, RSS, and search sources', () => {
  assert.equal(getCandidateAcquisitionLabel({
    explanation: { acquisitionMechanism: 'observed_dom' },
  }), 'YouTube native page');
  assert.equal(getCandidateAcquisitionLabel({
    explanation: { acquisitionMechanism: 'rss' },
  }), 'RSS discovery');
  assert.equal(getCandidateAcquisitionLabel({
    provenance: { mechanism: 'web_search', acquired_at: '2026-10-01T10:00:00.000Z' },
  }), 'YouTube search discovery');
  assert.equal(getCandidateAcquisitionLabel({
    acquisition_history: [
      { mechanism: 'rss', acquired_at: '2026-10-01T09:00:00.000Z' },
      { mechanism: 'web_search', acquired_at: '2026-10-01T11:00:00.000Z' },
    ],
  }), 'YouTube search discovery');
});

test('explanation view model exposes acquisition source even without graph/history support', () => {
  const view = buildExplanationViewModel({
    external_id: 'rss-ai',
    title: 'AI candidate',
    score: 50,
    traceId: 'trace-rss-ai',
    provenance: { mechanism: 'rss', acquired_at: '2026-10-01T10:00:00.000Z' },
    explanation: {
      rawScore: 0,
      displayScore: 50,
      graphRevision: 9,
      acquisitionMechanism: 'rss',
      contributions: [],
      matchedPaths: [],
      modeGrounding: null,
      historySupport: null,
    },
  });
  assert.equal(view.sourceLabel, 'RSS discovery');
  assert.match(view.acquisitionLine, /RSS discovery/);
  assert.deepEqual(view.contributions, []);
  assert.deepEqual(view.historyMatches, []);
});
